// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package scanerr

import (
	"github.com/libmonsoon-dev/scanerr/config"
	"github.com/libmonsoon-dev/scanerr/internal/packages"
	"github.com/libmonsoon-dev/scanerr/internal/scanerr"
	"github.com/libmonsoon-dev/scanerr/internal/source"
	"github.com/libmonsoon-dev/scanerr/internal/unfmt"
)

// Injectors from app.go:

func NewScanerr(configConfig config.Config) *scanerr.Scanner {
	loaderConfig := configConfig.PackagesLoaderConf
	loader := packages.NewLoader(loaderConfig)
	stringsExtractorConfig := configConfig.StringsExtractorConfig
	stringsExtractor := source.NewStringsExtractor(stringsExtractorConfig)
	stringMatcher := unfmt.NewMatcher()
	scanner := scanerr.NewScanner(loader, stringsExtractor, stringMatcher)
	return scanner
}
