// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/libmonsoon-dev/scanerr/config"
	"github.com/libmonsoon-dev/scanerr/packages"
	"github.com/libmonsoon-dev/scanerr/scanerr"
	"github.com/libmonsoon-dev/scanerr/source"
	"github.com/libmonsoon-dev/scanerr/unfmt"
)

// Injectors from app.go:

func NewScanerr(configConfig config.Config) *scanerr.Scanerr {
	loaderConfig := configConfig.PackagesLoaderConf
	loader := packages.NewLoader(loaderConfig)
	stringsExtractorConfig := configConfig.StringsExtractorConfig
	stringsExtractor := source.NewStringsExtractor(stringsExtractorConfig)
	stringMatcher := unfmt.NewMatcher()
	scanerrScanerr := scanerr.NewScanerr(loader, stringsExtractor, stringMatcher)
	return scanerrScanerr
}
