// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"github.com/libmonsoon-dev/scanerr/config"
	"github.com/libmonsoon-dev/scanerr/packages"
	"github.com/libmonsoon-dev/scanerr/scanerr"
	"github.com/libmonsoon-dev/scanerr/searcher"
	"github.com/libmonsoon-dev/scanerr/source"
)

// Injectors from app.go:

func NewScanerr(configConfig config.Config) *scanerr.Scanerr {
	scanerrConfig := configConfig.ScanerrConfig
	loaderConfig := configConfig.PackagesLoaderConf
	loader := packages.NewLoader(loaderConfig)
	stringsExtractorConfig := configConfig.StringsExtractorConfig
	stringsExtractor := source.NewStringsExtractor(stringsExtractorConfig)
	searcherSearcher := searcher.NewSearcher()
	scanerrScanerr := scanerr.NewScanerr(scanerrConfig, loader, stringsExtractor, searcherSearcher)
	return scanerrScanerr
}
